### ISSUE TITLE
FSRS Compatibility (Learn Now & Grade Now)

### ISSUE THREAD

**Issue by Exponent4806** [Ajatt-Tools/learn-now-button#2]
I started a discussion about the compatibility of this add-on with FSRS:

https://github.com/open-spaced-repetition/fsrs4anki/issues/540

Could you please help us to clarify this issue ?

It seems that the add-on is partially compatible, but I am not completely sure. It seems that using your add-on with the new algorithm FSRS might cause serious problems, and there is no warning about that.

**Comment by tatsumoto-ren** [comment]
> Could you please help us to clarify this issue ?

Looks like there's [a bug](https://github.com/open-spaced-repetition/fsrs4anki/issues/540#issuecomment-1821980545) in FSRS that prevents the add-on from being compatible. FSRS has to initialize the initial memory state when the card is learned but it fails to do so if a card was moved to the learning queue manually.

**Comment by KAGEYAM4** [comment]
This got implemented https://github.com/ankitects/anki/commit/db93939ded947d74bb25bd8552a2b2356a096509
