### ISSUE TITLE
Using `Lean Now` changes the order of cards

### ISSUE THREAD

**Issue by KAGEYAM4** [Ajatt-Tools/learn-now-button#3]
![image](https://github.com/Ajatt-Tools/learn-now-button/assets/75798544/a06ad89a-84ae-468b-8497-be37c54d4ff1)

Now when i stard the studying the deck the order becomes -> ` d b c a e`

-----------

Also there is inbuild option in `Browse Window` - `forget`, it shows different behavior like this ->

1. If i use `forget with both option checked`, the new  `Due order` is assigned number as what you actually see on the screen.
eg.  - 
![image](https://github.com/Ajatt-Tools/learn-now-button/assets/75798544/32d7f49e-4852-436a-abdc-5c7a4db813a2)

2. if i don't use `lean now` and study using default anki way, and use ` forget` , the ` Due order` is restored to what it was originally.

---------------------

![image](https://github.com/Ajatt-Tools/learn-now-button/assets/75798544/94bf7a1d-b7fa-43aa-9129-f6a4c6fed8a7)

**Comment by tatsumoto-ren** [comment]
Learn now doesn't change the order of cards, but it assigns due dates with some randomness to make sure that the order of cards doesn't affect retention. To properly restore cards to their original positions you need to use [this addon](https://tatsumoto.neocities.org/blog/useful-anki-add-ons-for-japanese#reset-card-scheduling).

**Comment by KAGEYAM4** [comment]
> Learn now doesn't change the order of cards, but it assigns due dates with some randomness to make sure that the order of cards doesn't affect retention.

is there a way to stop this randomness so that they appear in the same order while learning in which they were created.

I use 'lean now' when i have added bunch of cards to different decks for a day or two, i simply go into 'browse window', 'Added section' > select all > lean now

**Comment by tatsumoto-ren** [comment]
> is there a way to stop this randomness so that they appear in the same order while learning in which they were created.

There's no such option currently.

> I use 'lean now' when i have added bunch of cards to different decks for a day or two, i simply go into 'browse window', 'Added section' > select all > lean now

got it.

**Comment by KAGEYAM4** [comment]
> > is there a way to stop this randomness so that they appear in the same order while learning in which they were created.
> 
> There's no such option currently.

is there a chance of this getting implemented in future.

**Comment by tatsumoto-ren** [comment]
> is there a chance of this getting implemented in future.

If you want to implement this, you're welcome of course. 

upd: I had some time today, so I did it myself.

**Comment by KAGEYAM4** [comment]
Thank you so much.
